### ISSUE TITLE
Unknown error in import statement from dist dependency

### ISSUE THREAD

**Issue by davedbase** [pikapkg/cdn#117]
I'm trying to import `https://cdn.skypack.dev/solid-js/web/dist/server?dts` in my Deno project and hit the error:
```
error: Uncaught (in promise) Error: [Package Error] "stream" no dependency version info found. (Imported by "solid-js").
    at https://cdn.skypack.dev/error/unknown:stream?from=solid-js:13:7
```
I dug into the modules being served up and noticed the following at the top of https://cdn.skypack.dev/-/solid-js@v0.23.11-pnrJIYc8SvSWpmxDc57s/dist=es2020,mode=raw/web/dist/server.js?dts:
```js
import "/error/unknown:stream?from=solid-js";
;
```
I'm trying to trace where the came from and how it gets compiled that way but can't seem to track the source of the issue. At first I thought that perhaps the solid.js library was making use of Node.js standard Stream.

Searching the Solid repository, references to stream don't depend or import it directly: https://github.com/ryansolid/solid/search?q=stream.

This could be an issue within Skypack, the Solid library or maybe I'm not properly informed about how this works. I tried using a Deno import map to reference `stream` to `https://deno.land/std/node/stream` but that was futile.

Definitely a strange scenario.

**Comment by drwpow** [comment]
Ah, interesting. Yeah it seems that on the first line of [web/dist/server.js](https://unpkg.com/browse/solid-js@0.23.11/web/dist/server.js#L1), it imports the Node built-in `stream`:

```js
import { Readable } from 'stream';
```

However we seem to not be marking that as a Node built-in as we should! Thus the confusing error message. I’ll add this as a Node built-in, however, it may be difficult to get this working in Deno as it uses Node code.

**Comment by davedbase** [comment]
@drwpow thanks Drew. I don't see where that Readable is being pulled in. Where did you notice it???

I wont be using that stream function directly and Deno has a std Node compat option I can bind stream to located at: https://deno.land/std/node/stream. So I think I should be able to dodge this one if Skypack marks it properly.

Edit: ryansolid just made me aware that a dependency dom-expressions library actually pulls in Readable. Oops. Missed that.

**Comment by drwpow** [comment]
Experimenting with this a little bit more. This is where I’m at with that import:

```js
import { Readable } from 'node:stream';
```

Is this expected? When I try and run it, this is what I get:

```
error: Remote modules are not allowed to import local modules.  Consider using a dynamic import instead.
  Importing: node:stream
```

Is there a way that you can alias that to https://deno.land/std/node/stream on your end? Or would we need to do that in Skypack?

**Comment by davedbase** [comment]
@drwpow that's precisely what I was trying to do but the reference to "unknown:error" was prohibiting it. Technically using the import map alias should solve it. I'll give it a spin and let you know.

**Comment by drwpow** [comment]
Cool, that’s helpful. FWIW that‘s not on the CDN just yet; wanted to confirm before changing it.

**Comment by davedbase** [comment]
Yup no problem. Once it's live I'll be able to test it, but theoretically this *should* solve the problem nicely. Thanks!

**Comment by drwpow** [comment]
I’m not able to get this working with `node:stream`, but I was able to get it working with `stream`. From the [import maps docs](https://deno.land/manual/linking_to_external_code/import_maps#import-maps), I noticed this line:

> Current limitations
> supports only `file:`, `http:` and `https:` schemes

I think deno interprets `node:*` as a protocol, and still throws the “remote modules” error. Unless I’m missing something? This is the import map I was working with:

```js
{
  "imports": {
    "node:stream": "https://deno.land/std/node/stream" // ❌ this fails
    "stream": "https://deno.land/std/node/stream" // ✅ this works
  }
}
```

**Comment by davedbase** [comment]
That makes more sense and also explains why `unknown:error` would be interpreted the same way. I could have just aliased that path as well but had the same issue as `node:stream`.

**Comment by drwpow** [comment]
Update: this is now live! Please clear out your Deno cache and try to load the URL again. It should be loading Deno’s copy of `stream`. I can‘t verify that this package works as intended with Deno‘s polyfill, but hopefully this is at least a better experience.
